name: Deploy static content to Pages

on:
  # Ejecuta cuando se hace un push al branch por defecto (main)
  push:
    branches: ["main"]

  # Permite ejecutar el flujo manualmente desde la pestaña de Actions
  workflow_dispatch:

# Establece permisos del GITHUB_TOKEN para permitir despliegues a GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue concurrente, sin cancelar los que están en progreso
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configura la acción de GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Sube el archivo `frontend/inicio.html` como un artefacto
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "frontend/inicio.html" # Especifica el archivo exacto que deseas subir

      # Despliega el archivo en GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # Indica que el contenido está en la ruta del archivo específico
          folder: "frontend"
